// lib/events.js

export const events = [
  {
    id: "taco-fiesta",
    title: "Taco Tuesday Fiesta",
    date: "2025-04-08T19:00:00Z",
    image: "/imgs/popup1.png",
    description:
      "Join us for a fun‑filled fiesta with tacos, margaritas, and great company.",
    status: "open",
    location: "Vesterbro, Copenhagen",
    tags: ["mexican", "tacos", "party"],
    price: "DKK 175",
    capacity: 40,
    hosts: ["Juan", "Maja"],
    dressCode: "Casual",
    featured: false,
  },
  {
    id: "food-fight",
    title: "Food Fight Fun",
    date: "2025-04-28T12:00:00Z",
    image: "/imgs/popup2.png",
    description: "It’s a delicious showdown—who will be the last one standing?",
    status: "sold out",
    location: "Nørrebro, Copenhagen",
    tags: ["fun", "food", "game"],
    price: "DKK 150",
    capacity: 30,
    hosts: ["Ella"],
    dressCode: "Playful",
    featured: false,
  },
  {
    id: "sunset-supper",
    title: "Sunset Supper Club",
    date: "2025-05-15T18:30:00Z",
    image: "/imgs/popup3.png",
    description: "Dine al fresco as the Copenhagen skyline glows at sunset.",
    status: "open",
    location: "Østerbro Rooftop",
    tags: ["sunset", "dining"],
    price: "DKK 325",
    capacity: 25,
    hosts: ["Juan"],
    dressCode: "Smart Casual",
    featured: true,
  },
  {
    id: "berry-bonanza",
    title: "Berry Bonanza Brunch",
    date: "2025-05-22T11:00:00Z",
    image: "/imgs/popup4.png",
    description:
      "A brunch bursting with seasonal berries, pastries, and prosecco.",
    status: "open",
    location: "Frederiksberg Garden",
    tags: ["brunch", "berries"],
    price: "DKK 195",
    capacity: 35,
    hosts: ["Sofie"],
    dressCode: "Garden Party",
    featured: false,
  },
  {
    id: "street-market",
    title: "Street Market Mingle",
    date: "2025-06-05T14:00:00Z",
    image: "/imgs/popup1.png",
    description:
      "Discover local makers, street food stalls, and live music downtown.",
    status: "sold out",
    location: "Kødbyen",
    tags: ["street food", "market"],
    price: "Free Entry",
    capacity: 200,
    hosts: ["Cozy Team"],
    dressCode: "Casual",
    featured: false,
  },
  {
    id: "garden-gala",
    title: "Garden Gala Evening",
    date: "2025-06-20T17:00:00Z",
    image: "/imgs/popup2.png",
    description:
      "An elegant evening amongst the blooms with cocktails and canapés.",
    status: "open",
    location: "Botanical Garden",
    tags: ["elegant", "outdoors"],
    price: "DKK 395",
    capacity: 50,
    hosts: ["Juan", "Liva"],
    dressCode: "Formal Garden Attire",
    featured: true,
  },
  {
    id: "midsummer-feast",
    title: "Midsummer Feast",
    date: "2025-07-12T13:00:00Z",
    image: "/imgs/popup3.png",
    description:
      "Celebrate midsummer with a long communal table and Nordic flavors.",
    status: "open",
    location: "Amager Beach",
    tags: ["summer", "nordic food"],
    price: "DKK 295",
    capacity: 60,
    hosts: ["Cozy Team"],
    dressCode: "White & Floral",
    featured: true,
  },
  {
    id: "harbor-hangout",
    title: "Harbor Hangout",
    date: "2025-07-28T16:00:00Z",
    image: "/imgs/popup4.png",
    description:
      "Casual gathering by the water with seafood platters and chilled rosé.",
    status: "sold out",
    location: "Nordhavn",
    tags: ["seafood", "summer"],
    price: "DKK 225",
    capacity: 40,
    hosts: ["Frederik"],
    dressCode: "Beach Casual",
    featured: false,
  },
  {
    id: "artisanal-afternoon",
    title: "Artisanal Afternoon Tea",
    date: "2025-08-10T15:00:00Z",
    image: "/imgs/popup1.png",
    description: "Hand‑crafted pastries, fine teas, and a genteel atmosphere.",
    status: "open",
    location: "The Tea Room, Indre By",
    tags: ["tea", "pastries"],
    price: "DKK 185",
    capacity: 20,
    hosts: ["Cecilie"],
    dressCode: "Elegant Afternoon",
    featured: false,
  },
  {
    id: "picnic-in-the-park",
    title: "Picnic in the Park",
    date: "2025-08-25T12:30:00Z",
    image: "/imgs/popup2.png",
    description: "Build your own picnic basket and relax under the trees.",
    status: "open",
    location: "Fælledparken",
    tags: ["picnic", "outdoor"],
    price: "DKK 150",
    capacity: 50,
    hosts: ["Cozy Crew"],
    dressCode: "Comfy & Cute",
    featured: false,
  },
  {
    id: "riverfront-roast",
    title: "Riverfront Roast Party",
    date: "2025-09-05T18:00:00Z",
    image: "/imgs/popup3.png",
    description:
      "Hearty roasts, craft beers, and live folk music by the river.",
    status: "open",
    location: "Christianshavn",
    tags: ["roast", "beer", "folk music"],
    price: "DKK 275",
    capacity: 45,
    hosts: ["Jakob"],
    dressCode: "Rustic Vibes",
    featured: false,
  },
  {
    id: "september-street-bites",
    title: "September Street Bites",
    date: "2025-09-18T17:30:00Z",
    image: "/imgs/popup4.png",
    description:
      "A curated selection of international street flavors in one place.",
    status: "sold out",
    location: "Reffen",
    tags: ["street food", "international"],
    price: "DKK 125",
    capacity: 70,
    hosts: ["Cozy Collective"],
    dressCode: "Street Style",
    featured: false,
  },

  {
    id: "test-june",
    title: "Debug Test Event",
    date: "2025-06-10T14:00:00Z",
    image: "/imgs/popup3.png",
    description: "Test event to check rendering.",
    status: "open",
    location: "Somewhere",
    tags: [],
    price: "Free",
    capacity: 10,
    hosts: ["Debug Bot"],
    dressCode: "None",
    featured: false,
  },
];
